---

- name: "Imperative: Run a tmsh command"
  hosts: bigips
  gather_facts: False
  connection: local

  vars_prompt:
    - name: "bigip_user"
      prompt: "Enter BIG-IP username"
      private: yes
    - name: "bigip_pass"
      prompt: "Enter BIG-IP password"
      private: yes

  tasks:
    - name: View system version and LTM configuration
      bigip_command:
        commands:
          - list /ltm virtual all
          - list /ltm pool all
          - list /ltm node all
        server: "{{ inventory_hostname }}"
        password: "{{ bigip_pass }}"
        user: "{{ bigip_user }}"
        validate_certs: no
      register: result


    - debug: msg="{{ result.stdout_lines }}"
